### ISSUE TITLE
Crashed the Facets module.

### ISSUE THREAD

**Issue by kylehuynh205** [digitalutsc/facets_year_range#5]
https://memory.digital.utsc.utoronto.ca/search-results?a%5B0%5D%5Bf%5D=all&a%5B0%5D%5Bi%5D=IS&a%5B0%5D%5Bv%5D=&f%5B1%5D=publication_date%3A%28min%3A1980%2Cmax%3A1985%29

````
TypeError: str_starts_with(): Argument #1 ($haystack) must be of type string, array given in str_starts_with() (line 50 of /var/www/D10-memory/web/modules/contrib/facets/src/Plugin/facets/query_type/SearchApiString.php).
````

````
#0 /var/www/D10-memory/web/modules/contrib/facets/src/Plugin/facets/query_type/SearchApiString.php(50): str_starts_with()
#1 /var/www/D10-memory/web/modules/contrib/facets/src/FacetManager/DefaultFacetManager.php(167): Drupal\facets\Plugin\facets\query_type\SearchApiString->execute()
#2 /var/www/D10-memory/web/modules/contrib/facets/src/EventSubscriber/SearchApiSubscriber.php(51): Drupal\facets\FacetManager\DefaultFacetManager->alterQuery()
#3 [internal function]: Drupal\facets\EventSubscriber\SearchApiSubscriber->queryAlter()
#4 /var/www/D10-memory/web/core/lib/Drupal/Component/EventDispatcher/ContainerAwareEventDispatcher.php(111): call_user_func()
#5 /var/www/D10-memory/web/modules/contrib/search_api/src/Query/Query.php(597): Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher->dispatch()
#6 /var/www/D10-memory/web/modules/contrib/search_api/src/Plugin/views/cache/SearchApiCachePluginTrait.php(206): Drupal\search_api\Query\Query->preExecute()
#7 /var/www/D10-memory/web/modules/contrib/search_api/src/Plugin/views/cache/SearchApiCachePluginTrait.php(173): Drupal\search_api\Plugin\views\cache\SearchApiTagCache->generateResultsKey()
#8 /var/www/D10-memory/web/core/modules/views/src/ViewExecutable.php(1478): Drupal\search_api\Plugin\views\cache\SearchApiTagCache->cacheGet()
#9 /var/www/D10-memory/web/core/modules/views/src/ViewExecutable.php(1513): Drupal\views\ViewExecutable->execute()
#10 /var/www/D10-memory/web/core/modules/views/src/Plugin/views/display/Page.php(201): Drupal\views\ViewExecutable->render()
#11 /var/www/D10-memory/web/core/modules/views/src/ViewExecutable.php(1689): Drupal\views\Plugin\views\display\Page->execute()
#12 /var/www/D10-memory/web/core/modules/views/src/Element/View.php(81): Drupal\views\ViewExecutable->executeDisplay()
#13 [internal function]: Drupal\views\Element\View::preRenderViewElement()
#14 /var/www/D10-memory/web/core/lib/Drupal/Core/Security/DoTrustedCallbackTrait.php(113): call_user_func_array()
#15 /var/www/D10-memory/web/core/lib/Drupal/Core/Render/Renderer.php(870): Drupal\Core\Render\Renderer->doTrustedCallback()
#16 /var/www/D10-memory/web/core/lib/Drupal/Core/Render/Renderer.php(432): Drupal\Core\Render\Renderer->doCallback()
#17 /var/www/D10-memory/web/core/lib/Drupal/Core/Render/Renderer.php(248): Drupal\Core\Render\Renderer->doRender()
#18 /var/www/D10-memory/web/core/lib/Drupal/Core/Render/MainContent/HtmlRenderer.php(238): Drupal\Core\Render\Renderer->render()
#19 /var/www/D10-memory/web/core/lib/Drupal/Core/Render/Renderer.php(638): Drupal\Core\Render\MainContent\HtmlRenderer->Drupal\Core\Render\MainContent\{closure}()
#20 /var/www/D10-memory/web/core/lib/Drupal/Core/Render/MainContent/HtmlRenderer.php(239): Drupal\Core\Render\Renderer->executeInRenderContext()
#21 /var/www/D10-memory/web/core/lib/Drupal/Core/Render/MainContent/HtmlRenderer.php(128): Drupal\Core\Render\MainContent\HtmlRenderer->prepare()
#22 /var/www/D10-memory/web/core/lib/Drupal/Core/EventSubscriber/MainContentViewSubscriber.php(90): Drupal\Core\Render\MainContent\HtmlRenderer->renderResponse()
#23 [internal function]: Drupal\Core\EventSubscriber\MainContentViewSubscriber->onViewRenderArray()
#24 /var/www/D10-memory/web/core/lib/Drupal/Component/EventDispatcher/ContainerAwareEventDispatcher.php(111): call_user_func()
#25 /var/www/D10-memory/vendor/symfony/http-kernel/HttpKernel.php(186): Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher->dispatch()
#26 /var/www/D10-memory/vendor/symfony/http-kernel/HttpKernel.php(76): Symfony\Component\HttpKernel\HttpKernel->handleRaw()
#27 /var/www/D10-memory/web/core/lib/Drupal/Core/StackMiddleware/Session.php(53): Symfony\Component\HttpKernel\HttpKernel->handle()
#28 /var/www/D10-memory/web/core/lib/Drupal/Core/StackMiddleware/KernelPreHandle.php(48): Drupal\Core\StackMiddleware\Session->handle()
#29 /var/www/D10-memory/web/core/lib/Drupal/Core/StackMiddleware/ContentLength.php(28): Drupal\Core\StackMiddleware\KernelPreHandle->handle()
#30 /var/www/D10-memory/web/core/modules/big_pipe/src/StackMiddleware/ContentLength.php(32): Drupal\Core\StackMiddleware\ContentLength->handle()
#31 /var/www/D10-memory/web/core/modules/page_cache/src/StackMiddleware/PageCache.php(106): Drupal\big_pipe\StackMiddleware\ContentLength->handle()
#32 /var/www/D10-memory/web/core/modules/page_cache/src/StackMiddleware/PageCache.php(85): Drupal\page_cache\StackMiddleware\PageCache->pass()
#33 /var/www/D10-memory/web/core/lib/Drupal/Core/StackMiddleware/ReverseProxyMiddleware.php(48): Drupal\page_cache\StackMiddleware\PageCache->handle()
#34 /var/www/D10-memory/web/core/lib/Drupal/Core/StackMiddleware/NegotiationMiddleware.php(51): Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle()
#35 /var/www/D10-memory/web/core/lib/Drupal/Core/StackMiddleware/AjaxPageState.php(36): Drupal\Core\StackMiddleware\NegotiationMiddleware->handle()
#36 /var/www/D10-memory/web/core/lib/Drupal/Core/StackMiddleware/StackedHttpKernel.php(51): Drupal\Core\StackMiddleware\AjaxPageState->handle()
#37 /var/www/D10-memory/web/core/lib/Drupal/Core/DrupalKernel.php(741): Drupal\Core\StackMiddleware\StackedHttpKernel->handle()
#38 /var/www/D10-memory/web/index.php(19): Drupal\Core\DrupalKernel->handle()
#39 {main}
````

**Comment by kylehuynh205** [comment]
https://memory.digital.utsc.utoronto.ca/search-results?a[0][f]=all&a[0][i]=IS&a[0][v]=&f[1]=publication_date:(min:1980,max:1985)
https://memory.digital.utsc.utoronto.ca/search-results?a[0][f]=all&a[0][i]=IS&a[0][v]=&f[1]=publication_date_range:(min:1980,max:1985)
